# Generated by Django 4.0 on 2022-02-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_img',
            field=models.ImageField(blank=True, default='./static/img/airplane.png', null=True, upload_to='instagram/'),
        ),
    ]
