# Generated by Django 4.0 on 2022-02-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_alter_post_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_img',
            field=models.ImageField(blank=True, default='./static/img/person.png', null=True, upload_to='instagram/'),
        ),
    ]
