# Generated by Django 4.0 on 2022-01-20 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=40, null=True)),
                ('imgfile_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_name_1', models.TextField(max_length=20)),
                ('imgfile_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_name_2', models.TextField(max_length=20)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(max_length=40)),
                ('choice', models.CharField(choices=[('1', 'First'), ('2', 'Second')], max_length=1)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('vote_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.vote_post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.comment')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.vote_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
