# Generated by Django 4.0 on 2022-01-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote_post',
            name='imgfile_1',
            field=models.ImageField(blank=True, null=True, upload_to='vote/'),
        ),
        migrations.AlterField(
            model_name='vote_post',
            name='imgfile_2',
            field=models.ImageField(blank=True, null=True, upload_to='vote/'),
        ),
    ]
