# Generated by Django 4.0 on 2022-01-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_vote_post_imgfile_1_alter_vote_post_imgfile_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ip',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='vote_post',
            name='img_name_1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vote_post',
            name='img_name_2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vote_post',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
