# Generated by Django 4.0 on 2022-01-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_participant_ip_alter_vote_post_img_name_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='choice',
            field=models.CharField(max_length=10),
        ),
    ]
