# Generated by Django 4.0 on 2022-01-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='entertain_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
