# Generated by Django 4.0 on 2022-02-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypage',
            name='color',
            field=models.CharField(default='black', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mypage',
            name='profile_img',
            field=models.ImageField(blank=True, default='./static/img/board1.png', null=True, upload_to='accounts/'),
        ),
    ]
