# Generated by Django 4.0 on 2022-02-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_mypage_color_alter_mypage_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(default='black', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='./static/img/board1.png', null=True, upload_to='accounts/'),
        ),
        migrations.DeleteModel(
            name='Mypage',
        ),
    ]
